language: node_js
dist: xenial
os: linux
node_js:
  - '12'
before_install:
  - npm install yarn -g
install:
  - yarn
before_script:
  - export TRAVIS_DIST=element-ui-helper-$TRAVIS_TAG.vsix
script:
  - yarn pretest
  - yarn package
before_deploy:
  - yarn package -o $TRAVIS_DIST
deploy:
  provider: releases
  token: $GITHUB_TOKEN
  file: $TRAVIS_DIST
  cleanup: false
  on:
    tags: true
after_deploy:
  - yarn changelog
  - yarn vsce publish --packagePath $TRAVIS_DIST
